all:
  children:
    k8s_control_plane:
      hosts:
        node-01:
          ansible_host: 192.168.1.101
    k8s_workers:
      hosts:
        node-02:
          ansible_host: 192.168.1.102
        node-03:
          ansible_host: 192.168.1.103
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
