- name: Kubernetes apt キーを追加
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    state: present

- name: Kubernetes リポジトリを追加
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"

- name: kubeadm・kubelet・kubectl をインストール
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: true

- name: kubelet を有効化
  service:
    name: kubelet
    enabled: true
